// Recorded sample pitch/velocity selection and the shared arrangement render.
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
const c=vm.createContext({Math,Blob,Float32Array,Float64Array,Uint8Array,ArrayBuffer,DataView,setTimeout});
for(const f of ['analysis','performance','synthesis','song-instruments','arrangement'])vm.runInContext(fs.readFileSync(path.join(root,'js/audio',f+'.js'),'utf8'),c);
const A=c.ScuLaArrangement,rate=22050;
const tone=(midi,dynamic,amplitude=.5)=>({midiNote:midi,dynamic,sampleRate:rate,channels:[Float32Array.from({length:rate},(_,i)=>amplitude*Math.sin(i*2*Math.PI*220/rate))]});
const low=tone(60,'pp'),high=tone(67,'ff');
assert.equal(A.mapSample([low,high],62,30),low);
assert.equal(A.mapSample([low,high],66,120),high);
assert.equal(A.mapSample([low],65,90),low);
assert.equal(A.mapSample([low],66,90),null,'more than five semitones must use synthesis');
assert.equal(A.mapSample([tone(60,'pp'),tone(60,'ff')],60,120).dynamic,'ff');
assert.equal(A.mapSample([tone(60,'pp'),tone(60,'ff')],60,20).dynamic,'pp');
assert.equal(A.mapSample([{...low,midiNote:null},low],60,80),low);
assert.equal(A.sampleVelocity('constructor'),80);
const note={start:0,dur:.3,midi:60,vel:.8,velocity:102,cents:0};
const arrangement={tempoBpm:120,timingMode:'original',key:{tonic:0,mode:'major'},duration:.5,parts:{lead:{instrument:'piano',sampleSet:'Flute',enabled:true,volume:1,notes:[note]},chords:{instrument:'strings',enabled:false,volume:1,notes:[]},bass:{instrument:'bass',enabled:false,volume:1,notes:[]},drums:{instrument:'standard',enabled:false,volume:1,notes:[]}}};
const energy=(x,start=0,end=x.length)=>x.slice(start,end).reduce((sum,v)=>sum+v*v,0);
(async()=>{
 const options={sampleRate:rate,yieldUI:()=>Promise.resolve()};
 const sampled=await A.render(arrangement,{...options,samples:{Flute:[low]}});
 const missing=await A.render(arrangement,options);
 assert.ok(energy(sampled.L)>0 && energy(missing.L)>0);
 assert.notDeepEqual(sampled.L,missing.L,'missing set must use selected synth instrument');
 const crossings=x=>{let count=0;for(let i=Math.round(.02*rate)+1;i<Math.round(.2*rate);i++)if(x[i-1]<=0&&x[i]>0)count++;return count;};
 arrangement.parts.lead.notes=[{...note,midi:65}];
 const shifted=await A.render(arrangement,{...options,samples:{Flute:[low]}});
 assert.ok(crossings(shifted.L)>crossings(sampled.L)*1.2,'pitch mapping must resample the source at the target pitch');
 arrangement.parts.lead.notes=[note];
 const stereo={...low,channels:[low.channels[0],Float32Array.from(low.channels[0],v=>-v)]};
 const twoChannels=await A.render(arrangement,{...options,samples:{Flute:[stereo]}});
 assert.ok(twoChannels.L[Math.round(.02*rate)]*twoChannels.R[Math.round(.02*rate)]<0,'stereo sample channels must remain distinct');
 assert.ok(energy(sampled.L,Math.round(.45*rate),Math.round(.55*rate))<energy(sampled.L,Math.round(.05*rate),Math.round(.15*rate))*.01,'note release must fade');
 arrangement.parts.lead.notes=[{...note,velocity:30,vel:30/127}];
 const soft=await A.render(arrangement,{...options,samples:{Flute:[low]}});
 assert.ok(energy(soft.L)<energy(sampled.L)*.5,'velocity must change sample loudness');
 arrangement.parts.lead.notes=[{...note,midi:72}];
 const distant=await A.render(arrangement,{...options,samples:{Flute:[low]}});
 const synth=await A.render(arrangement,options);
 assert.deepEqual(distant.L,synth.L,'distant samples must fall back to synthesis');
 const wav=Buffer.from(await A.wav(sampled).arrayBuffer());
 assert.equal(wav.readUInt16LE(22),2);assert.equal(wav.readUInt32LE(24),rate);
 assert.ok(wav.subarray(44).some(Boolean));
 console.log('PASS  nearest pitch and dynamic layers, audible pitch shift, stereo channels, shift limit, fallback, velocity, release and WAV');
})().catch(e=>{console.error(e);process.exitCode=1;});
